<?= $this->layout('layouts/layout') ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 400px;">
   <h1 class="text-danger display-3 mx-auto">Welcome</h1>
   <p class="lead w-75 mx-auto">To a modern lightweight PHP framework inspired by ASP.NET Core</p>
   <a class="btn btn-danger text-white mx-auto" href="https://devnet-framework.github.io">Get Started</a>
</div>
