<!DOCTYPE html>
<html lang="en">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
   <title>Artister - DevNet Framework</title>
   <!-- styles -->
   <link href="<?= url('lib/bootstrap/css/bootstrap.min.css') ?>" type="text/css" rel="stylesheet"/>
</head>
<body>
   <header>
      <?= $this->renderPartial('layouts/navbar') ?>
   </header>
   <main>
      <?= $this->renderBody() ?>
   </main>
  <!-- scripts -->
  <script src="<?= url('lib/bootstrap/js/bootstrap.bundle.min.js') ?>"></script>
  </body>
</html>