<nav class="navbar navbar-expand-md navbar-light bg-light bg-white border-bottom shadow-sm mb-3">
   <div class="container">
      <a class="navbar-brand" href="<?= url('/') ?>">DevNet</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto mb-lg-0">
            <li class="nav-item">
               <a class="nav-link active" aria-current="page" href="<?= url('/') ?>">Home</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="#">About</a>
            </li>
         </ul>
         <ul class="navbar-nav ml-auto mb-lg-0">
            <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                  Account
               </a>
               <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="<?= url('/account') ?>">My Account</a></li>
                  <li><a class="dropdown-item" href="<?= url('/account/register') ?>">Register</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="<?= url('/account/logout') ?>">Log Out</a></li>
               </ul>
            </li>
         </ul>
      </div>
   </div>
</nav>