<?= $this->layout('layouts/layout') ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 400px;">
      <h1 class="text-info display-3 mx-auto">Hello!</h1>
      <h6 class="text-info display-6 mx-auto"><?= $this->ViewData['Email'] ?></h6>
      <p class="lead">Click on the log out button to close your session.</p>
      <a class="btn btn-info text-white mx-auto" href=<?= url('/account/logout') ?>>Log Out</a>
</div>
