<?= $this->layout('layouts/layout') ?>

<br>
<div class="mx-auto p-5 shadow rounded" style="max-width: 400px">
    <form method="post" action="<?= url('/account/login') ?>">
        <h2 class="text-center text-info">Sign In</h2>
        <div class="mb-3">
            <label for="InputEmail" class="form-label">Email address</label>
            <input type="email" class="form-control" id="InputEmail" name="Username" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="InputPassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="InputPassword" name="Password">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="InputRemember" name="Remember">
            <label class="form-check-label" for="InputRemember">Remember me</label>
        </div>
        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-info text-white">Sign In</button>
        </div>
        <div class="text-center mt-3">
            Don't have an account? <a href="<?= url('/account/register') ?>">Sign Up.</a>
        </div>
    </form>
</div>
